config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :devices do
    resources :reservations
  end
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  include PgSearch::Model
  DEVICE_TYPE = ['Traditionnel', 'Electrique']
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :name, :device_type, :capacity, :address, :price, presence: true
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  pg_search_scope :search_by_all_fields,
    against: [ :name, :brand, :device_type, :capacity ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :device
  validates :start_date, :end_date, :total_price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
  has_many :devices
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @devices = policy_scope(Device).search_by_all_fields(params[:query])
    else
      @devices = policy_scope(Device)
    end
    @markers = @devices.geocoded.map do |device|
      {
        lat: device.latitude,
        lng: device.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { device: device })
      }
    end
  end

  def show
    @device = Device.find(params[:id])
    @reservation = Reservation.new
    authorize @device
  end

  def new
    @device = current_user.devices.new
    authorize @device
  end

  def create
    @device = current_user.devices.new(device_params)
    authorize @device
    if @device.save
      flash[:notice] = 'Votre appareil a bien été ajouté'
      redirect_to device_path(@device)
    else
      render :new
    end
  end

  def edit
    @device = Device.find(params[:id])
    authorize @device
  end

  def update
    @device = Device.find(params[:id])
    authorize @device
    @device.update(device_params)
    redirect_to device_path(@device)
  end

  def destroy
    @device = device.find(params[:id])
    authorize @device
    @device.destroy
    redirect_to devices_path
  end

  private

  def device_params
    params.require(:device).permit(:user_id, :name, :device_type, :capacity, :brand, :address, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
    authorize @reservation
    @device = Device.find(params[:device_id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @device = Device.find(params[:device_id])
    @reservation.device = @device
    @reservation.user = current_user
    @reservation.total_price = @device.price * (@reservation.end_date - @reservation.start_date).to_i
    if @reservation.save
      flash[:notice] = 'Votre réservation a bien été enregistrée'
      redirect_to dashboard_path
    else
      flash[:notice] = 'Il y a une erreur, veuillez réessayer'
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end

  def update
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.update(reservation_params)
    redirect_to reservation_path(@reservation)
  end

  def destroy
    @reservation = reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy
    redirect_to dashboard_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :total_price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/_info_window.html.erb
<h2 ><%= link_to device.name, device_path(device) %></h2>
<p><%= link_to cl_image_tag device.photos.first.key, height: 120, width: 160, crop: :fill %></p>

app/views/devices/index.html.erb
<div class="margin-constraint">
  <br>
  <br>
    <%= form_tag devices_path, method: :get do %>
      <div style="display: flex">
        <%= text_field_tag :query, params[:query], class: "form-control rounded", placeholder: "Trouvez votre appareil" %>
        <%= submit_tag "Rechercher", class: "input-group-text border-0", id: "search-addon" %>
      <% end %>
    </div>
  <div class="devices-and-map row">
    <div class="devices col-8">
      <h1>Les <%= @devices.count %> appareils à louer</h1>
      <ul class="articles">
        <% @devices.each do |device| %>
        <li> <%= link_to device_path(device) do %>
          <div class="card-product-index">
            <%= cl_image_tag device.photos.first.key %>
            <div>
              <h2 class="card-product-index-title">Appareil <%= device.device_type %></h2>
                <h5><em><%= device.brand %></em></h5>
              <div class="card-product-index-infos">
                <h3 class="card-product-index-capacity"><%= device.capacity %> <i class="fas fa-users"></i></h3>
                <h3 class="card-product-index-pricing"><%= device.price %> €</h3>
              </div>
            </div>
          </div>
        </li>
        <% end %>
        <% end %>
      </ul>
    </div>
    <div class="map col-4">
      <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        <!-- style="width: 40vw; height: 100vh;" -->
      </div>
    </div>
  </div>
</div>

app/views/devices/new.html.erb
<div class="banner" id="login-user"style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/TVxI-vkmTLI/1900x1200);">
<div class="form-container">
<%= simple_form_for @device do |f| %>
  <%= f.input :name %>
  <%= f.input :device_type, collection: Device::DEVICE_TYPE %>
  <%= f.input :brand %>
  <%= f.input :capacity, input_html: { min: '0' } %>
  <%= f.input :price, input_html: { min: '0' } %>
  <%= f.input :address %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>
</div>
</div>

app/views/devices/show.html.erb
<div class="container">
  <%= link_to 'Retour aux recherches', devices_path, class: "button-search" %>
  <div class="product-and-reservation">
    <div class="product-container">
      <div class="card-product-show">
        <% @device.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
          <div class="card-product-infos-show">
            <h2 class="product-name"><%= @device.name %></h2>
            <hr>
            <p><strong><span>Marque :</span></strong><span style="margin-left: 5px;"> <%= @device.brand %></span></p>
            <div class="capacity">
             <i class="fas fa-users"></i>
             <p> <%=@device.capacity %> personnes</p>
            </div>
            <div class="type">
              <i class="fas fa-bolt"></i>
              <p><strong><span>Type :</span></strong><span style="margin-left: 5px;"> <%= @device.device_type %></span></p>
            </div>
            <div class="price">
              <i class="fas fa-money-bill-wave"></i>
              <p id="euros"> <%= @device.price %> € / jour</p>
            </div>
        </div>
      </div>
      <div class="owner">
        <hr>
        <div class="user-show">
        <i class="far fa-user"></i>
        <p><strong><span>Loueur :</span></strong><span style="margin-left: 3px;"> <%= @device.user.first_name %></span style="margin-right: 3px;"></p>
        <p><strong><span>(<%=@device.user.reservations.count%></span style="margin-left: 3px;"></strong><span style="margin-left: 3px;"> réservation)</span></p>
        </div>
        <div class="address">
          <i class="fas fa-map-marker-alt"></i>
          <p> <strong> Addresse : </strong><%= @device.address%></p>
        </div>
        <div class="date">
        <i class="far fa-calendar-alt"></i>
        <p> <strong> Annonce créée le : </strong><%= @device.created_at%></p>
        </div>
      </div>
    </div>
    <div class="reservations-container">
     <div class="reservations text-center">
      <h4>Réservez votre appareil</h4>
    <%= simple_form_for [ @device, @reservation ] do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "Réserver", class: "reservation-button" %>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Racleat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" unless current_page?("controller"=>"devise/sessions", "action"=>"new")%>
    <div class="content-wrapper">
    <%= yield %>
    </div>
    <%= render "shared/footer"%>
    <%= render "shared/alerts"%>
 </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
<!--   <p> you can put here the user information</p>
  <p>Display the user reservations others raclette device</p>
  <p>Display the reservations for his raclette device if there is some</p>
  <p>for each reservation, add buttons to modify the reservation</p>
  <p> The user can only delete a reservation for his own raclette device that is booked by another user</p> -->
<div class="info-card-main">
  <div class="card-dashboard">
    <!-- user information box (maybe use card )-->
    <!-- maybe add avatar (same as navbar) -->
    <h5> <strong> Vos informations</strong> </h5>
      <div class="txt-dash-info">
        <p> Prénom :  <span> <%= @user.first_name %> </span></p>
      </div>
      <div class="txt-dash-info">
        <p> Nom :  <span> <%= @user.last_name %></span> </p>
      </div>
      <div class="txt-dash-info">
        <p> Email:  <span> <%= @user.email %> </span> </p>
      </div>
  </div>

  <div class="card-dashboard">
    <h5> <strong> Vos réservations</strong> </h5>
    <div class="txt-dash-resa">
      <p> Réservations en cours :  <span> <%= @user.reservations.count %> </span> </p>
    </div>
    <br>
    <br>
    <div class="txt-dash-resa">
    <p> Appareils en réservation :  <span> <%= @user.devices.count %> </span> </p>
    </div>
  </div>
</div>
  <hr>
  <br>

  <!-- bookings list - use cards like the index -->

    <ul class="list-inline tabs-underlined">
    <li>
      <a href="#" class="tab-underlined active" id="btn-resa">Vos réservations</a>
     </li>
     <li>
       <a href="#" class="tab-underlined" id="btn-loc">Vos appareils en location</a>
    </li>
  </ul>

  <div class="card-main" id="block-resa">

    <div class="cards-resa">
        <% @user.reservations.each do |reservation| %>
        <div class="card-product-dashboard">
          <%= cl_image_tag reservation.device.photos.first.key, class: "img", alt: "" %>
          <div class="card-product-dashboard-infos">
            <div class="card-product-dashboard-content">
            <h4> <%= reservation.device.name %> </h4>
            <p> Du <%= reservation.start_date.strftime("%d-%m-%Y") %> au <%= reservation.end_date.strftime("%d-%m-%Y") %> </p>
            <p> Adresse: <%= reservation.device.address %> </p>
            </div>
            <div class=dash-card-foot>
            <h4 class="dash-h3-pricing">  <%= reservation.total_price %> €</h4>
            <h4 class="card-product-dash-capacity"><%= reservation.device.capacity %> <i class="fas fa-users"></i></h4>
            <%= link_to "voir l'appareil", device_path(reservation.device), class:"show-link" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<!-- list of user devices -->
  <div class="card-main toggle-display" id="block-loc">
    <div class="cards-loc">
      <% @user.devices.each do |device| %>
      <div class="card-product-dashboard">
        <%= cl_image_tag device.photos.first.key, class: "img", alt: "" %>
        <div class="card-product-dashboard-infos">
          <div class="card-product-dashboard-content">
            <h4> <%= device.name %> </h4>
            <p> Disponible depuis : <%= device.created_at.strftime("%d-%m-%Y") %> </p>

            <p> Marque : <%= device.brand %> </p>
          </div>
          <div class=dash-card-foot>
            <h4 class="dash-h3-pricing">  <%= device.price %> €</h4>
            <h4 class="card-product-dash-capacity"><%= device.capacity %> <i class="fas fa-users"></i></h4>
            <%= link_to "voir l'appareil", device_path(device), class:"show-link" %>
          </div>
        </div>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/8EfaUXB8qw4/1900x1200);">
  <div class="container">
    <h1>Racleat !</h1>
    <h2><span id="banner-typed-text"></span></h2>
    <br>
    <br>
    <h4><em> Louez un appareil près de chez vous et profitez-en avec votre entourage!</em></h4>
    <br>
    <h4><em> Des appareils de choix et de qualité proposés par des particuliers</em></h4>
    <br>
    <br>
    <br>
    <br>
    <div class="btn-homepage">
      <%=link_to "Say cheese 🧀", devices_path, class: "btn btn-outline" %>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
<%= simple_form_for [@device, @reservation] do |f| %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <p> reservation price : <%= @device.price %> € </p>
  <%= f.submit %>
<% end %>
</div>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong>Yay!</strong> 🎉  <%= notice %> </span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/grambetta/racleat"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    We love <i class="fas fa-cheese"></i> !</i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand logo-name" do %>
    <%= image_tag "logo.jpg" %>
    <h1 id="racleat">Racleat</h1>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Nouvel appareil", new_device_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.bmwaganassociates.com/wp-content/uploads/2020/12/img_568656.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>